### ISSUE TITLE
How can i separate the Album and Artist? 

### ISSUE THREAD

**Issue by collette7** [tylerbouknight/obsidianDiscogs#1]
How can i separate the Album and Artist? vs the Data pulling in as "Artist" - "Album".
ie.
---
artist: {{VALUE:artistName}}
---

Seperately: how can I update linkify to parse it as links in the event there are multiple, id like to do the same with genres.

artist: {{VALUE:artistName}} would result in = [[John Coltrane]] [[Eric Dolphy]]
vs the current John Coltrane,Eric Dolphy

**Comment by tylerbouknight** [comment]
@cece554 If you’ve made any changes, feel free to submit a PR :)
